//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMusicLibrary.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMusicLibrary.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album cannot be empty..
        /// </summary>
        public static string ALBUM_EMPTY {
            get {
                return ResourceManager.GetString("ALBUM_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist album cannot be empty..
        /// </summary>
        public static string ARTIST_EMPTY {
            get {
                return ResourceManager.GetString("ARTIST_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No artist or band with that name was found..
        /// </summary>
        public static string ARTIST_NOTFOUND {
            get {
                return ResourceManager.GetString("ARTIST_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is already registered..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect..
        /// </summary>
        public static string INCORRECT_CURRENT_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("INCORRECT_CURRENT_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail or Password invalid..
        /// </summary>
        public static string LOGIN_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No music found..
        /// </summary>
        public static string MUSIC_EMPTY {
            get {
                return ResourceManager.GetString("MUSIC_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This song already exists and is not available for registration..
        /// </summary>
        public static string MUSIC_EXIST {
            get {
                return ResourceManager.GetString("MUSIC_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This song ID does not belong to you..
        /// </summary>
        public static string MUSIC_NOT_BELONG_TO_USER {
            get {
                return ResourceManager.GetString("MUSIC_NOT_BELONG_TO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token null or empty..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating playlist..
        /// </summary>
        public static string PLAYLIST_CREATE_ERROR {
            get {
                return ResourceManager.GetString("PLAYLIST_CREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist description must contain up to 500 characters..
        /// </summary>
        public static string PLAYLIST_DESCRIPTION_TOO_LONG {
            get {
                return ResourceManager.GetString("PLAYLIST_DESCRIPTION_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name cannot be null..
        /// </summary>
        public static string PLAYLIST_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PLAYLIST_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist name must be up to 100 characters long..
        /// </summary>
        public static string PLAYLIST_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("PLAYLIST_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist notfound..
        /// </summary>
        public static string PLAYLIST_NOTFOUND {
            get {
                return ResourceManager.GetString("PLAYLIST_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no playlists created..
        /// </summary>
        public static string PLAYLISTS_ALL_NOTFOUND {
            get {
                return ResourceManager.GetString("PLAYLISTS_ALL_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be the same as current..
        /// </summary>
        public static string SAME_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("SAME_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes made..
        /// </summary>
        public static string UPDATE_ERROR {
            get {
                return ResourceManager.GetString("UPDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update. Email already in use..
        /// </summary>
        public static string UPDATE_INVALID {
            get {
                return ResourceManager.GetString("UPDATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access..
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
    }
}
